os:
  - osx

language: node_js

if: tag IS present

cache:
  - yarn
  - $HOME/.electron
  - $HOME/.yarn
  - $HOME/Caches/electron-builde

node_js:
  - '8.11'

env:
    - TRAVIS_CI=TRAVIS_CI

script:
    - npm run release
