version: 0.1.{build}

branches:
  only:
    - master

image: Visual Studio 2017
platform:
  - x64

deploy:
  - provider: Environment
    name: production
    on:
      appveyor_repo_tag: true

cache:
  - node_modules
  - '%APPDATA%\npm-cache'
  - '%USERPROFILE%\.electron'
  - '%USERPROFILE%\AppData\Local\Yarn\cache'
  - '%LOCALAPPDATA%\Yarn'
  - '%LOCALAPPDATA%\electron-builder'

init:
  - git config --global core.autocrlf input

install:
  - ps: Install-Product node 8 x64
  - git reset --hard HEAD
  - yarn
  - node --version
  - yarn --version

build_script:
  - yarn run p

test: off
